### ISSUE TITLE
Publisher-location is not beeing shown

### ISSUE THREAD

**Issue by ScharlsLeGlerg** [typst/hayagriva#113]
### Description

When citing an item from the bibliography the location of the publisher does not get shown.
As can be seen in the reproduction URL this happens both in footnotes and in the bibliography.

It happens both with Biblatex and Hayagriva.

I tested it with a minimal CSL style that should only display the publisher location, with the in-built styles and other custom styles. 

### Reproduction URL

https://typst.app/project/rawjjHv7N1q_ZUACnpO4gG

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
Should be fixed with #105. The biblatex file works just like that, the hayagriva yaml file needs to be updated as the publisher location is now set in the `publisher` field:
```yaml
fleischmann2008:
  type: book
  title: Rat und Patriziat in Nürnberg
  author: Fleischmann, Peter
  volume: 1
  publisher:
    location: Nürnberg
  date: 2008
```

Renders as (IEEE style)
> P. Fleischmann, _Rat und Patriziat in Nürnberg_, vol. 1. Nürnberg, 2008.
