### ISSUE TITLE
APA 7 - No title when referencing a book or article without author

### ISSUE THREAD

**Issue by cascading-jox** [typst/hayagriva#139]
I have an issue where the title of a source is suppressed when there is no author to the work. If I add a mock author it works as expected. This is the incorrect format that gets rendered now: 

```
In bibliography: (Date). Source.
In text: (year)

```
This is how I expect it to be formated:

```
In bibliography: Title. (Date). Source.
In text: (Title, year)
```

I am using the latest version of typst and this is the entry in the bibliography.yml file: 

```YML
ethics:
  type: Article
  title: "Good Research Practice"
  date: 2017
  publisher: Swedish Research Council
  url: https://www.vr.se/english/analysis/reports/our-reports/2017-08-31-good-research-practice.html
```

Here are the official APA guidelines for referencing sources with missing information: https://apastyle.apa.org/style-grammar-guidelines/references/missing-information

**Comment by cascading-jox** [comment]
I found a good enough workaround for any one that has similar issues. You can just put the title in the author field like this: 

```YML
ethics:
  type: Article
  author: "Good Research Practice"
  date: 2017
  publisher: Swedish Research Council
  url: https://www.vr.se/english/analysis/reports/our-reports/2017-08-31-good-research-practice.html
```
