### ISSUE TITLE
Bibliography Chicago Author-Date Period Error

### ISSUE THREAD

**Issue by zea-ai** [typst/hayagriva#146]
### Description

When using "chicago-author-date" for a bibliography: 

1. Periods are being placed beyond the terminal quote mark for article titles; and, 
2. Articles without urls are not taking periods after page ranges.

**main.typ**
```Typst
This is "a test" @test.

#bibliography("refs.yml",
style: "chicago-author-date"
)
```

**refs.yml**
```YAML
test:
  type: article
  title: A Test of Tests
  author: McTesterson, Testy
  page-range: 1–34
  date: 2024
  parent:
    title: Journal of Tests
    volume: 1
    issue: 1
```

**Generates**
This is “a test” (McTesterson 2024).
Bibliography
McTesterson, Testy. 2024. “A Test of Tests”. *Journal of Tests* 1 (1): 1–34

**Expected**
This is “a test” (McTesterson 2024).
Bibliography
McTesterson, Testy. 2024. “A Test of Tests.” *Journal of Tests* 1 (1): 1–34.

For this [journal article entry](https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html#cg-journal): 
- Period inside quote mark
- Period at end of entry

**Compiler Version:** Latest (Typst 0.11.0)

**Attempted Fix**
Downloading the CSL file, uploading it to the Typst project, and deleting the period from '<text macro="container-title" prefix=". "/> worked, but then every bibliographic entry needed a period at the end their titles. Is there a better way?

Thank you for looking into this. 

### Browsers

Chrome

### OS

macOS
