### ISSUE TITLE
APA bibliography is wrong with names with particles like "Joey de Vries"

### ISSUE THREAD

**Issue by St0wy** [typst/hayagriva#147]
### Description

If you add an author to a bibliography that has a particle name, it will not be shown according to the APA rules. For example if you add "Joey de Vries" as "de Vries, Joey" in the author field, it should be displayed as "de Vries, J." but it is displayed as "Vries, J. de.".

![image](https://github.com/typst/typst/assets/35960548/2ed0f988-8d7b-4131-906f-a76b965b29fb)

This can be worked around by using verbatim, but it's not ideal. For example:

```yaml
learn-opengl:
  type: web
  title: Shadow Mapping
  author:
    name: de Vries, J.
    verbatim: true
  url: https://learnopengl.com/Advanced-Lighting/Shadows/Shadow-Mapping
  parent:
    type: web
    title: Learn OpenGL
  date: 2014-06
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst
