### ISSUE TITLE
Allow multiple publishers

### ISSUE THREAD

**Issue by tingerrr** [typst/hayagriva#151]
Hayagriva should support sequences for publishers.

The book I am citing was published in cooperation by MIT press and McGraw-Hill. I can of course simply put both of them into a single publisher field, but once I translate my thesis, I will surely forget to change "und" to "and" in the formatted string.

Here is what I would've written:
```yaml
the-big-book:
  # ...
  publisher:
    - MIT Press
    - McGraw-Hill
  # ...
```

And here is what I ended up writing to work around this:
```yaml
the-big-book:
  # ...
  publisher: MIT Press und McGraw-Hill
  # ...
```

Here's the full citation for testing:
```yaml
the-big-book:
  type: book
  title: Introduction to Algorithms
  author:
    - Cormen, Thomas H.
    - Leiserson, Charles E.
    - Rivest, Ronald L.
    - Stein, Clifford
  edition: 3
  date: 2009
  publisher:
    - MIT Press
    - McGraw-Hill
  serial:
    isbn: 0-262-03384-4
```
