### ISSUE TITLE
`note` field has no effect

### ISSUE THREAD

**Issue by lukasjuhrich** [typst/hayagriva#167]
## [Repro](https://typst.app/project/rxIcN21BqJwsr3F4PiNTJ1):
```yml
kazda-moore:
  type: manuscript
  title: The Minion Homomorphism Lattice
  author:
    - "Kazda, Alexandr"
    - "Moore, Matthew"
  date: 2019
  note: "unpublished draft"
```
```typst
#set page(width: auto, height: auto, margin: 1em)
See @kazda-moore.

#cite(<kazda-moore>, form: "full")

#bibliography("bib.yml")
```
Renders:
![image](https://github.com/typst/hayagriva/assets/10060406/e48a3665-1229-4bfd-9ce2-1617088de1c5)

## expected
To have the `note` show up

## Remarks
This is related to #91, but seems orthogonal, because in that issue the problem was that the `bibtex` note field did not even make it to the hayagriva representation. Here, i'm giving it directly via `yml`, and it still does not show up.
