### ISSUE TITLE
Some DOIs fail to parse

### ISSUE THREAD

**Issue by miasb** [typst/hayagriva#178]
Hi,

i'm currently trying to do citations with clickable DOI links. It seems to work fine for all DOIs with numbers and letters in the link, but links with numbers don't show up for me.

Example: 
```
serial-number:                                                                          
  doi: 10.1007/3-540-12721-6
```

Can someone reproduce this?

**Comment by extua** [comment]
I'm trying to reproduce it, with this minimal example:

### main.typ
```typst
Book citation @density_book

#bibliography("citations.yml")
```

### citations.yml
```yml
density_book:
    type: book
    title: "Density Functional Theory"
    serial-number: 
      doi: 10.1007/3-540-12721-6 
```

Produces [this pdf](https://github.com/user-attachments/files/15957250/doi_bug.pdf) with a clickable link.

What kind of citation style are you using?

**Comment by miasb** [comment]
Thank you for the reply. I used the style "thieme". Omitting it solves the problem. Is this intentional behaviour?

**Comment by reknih** [comment]
> I used the style "thieme". Omitting it solves the problem. Is this intentional behaviour?

The Thieme style only prints the DOI for journal articles. Making the entry type article makes the DOI appear:

```yaml
density_book:
    type: article
    title: "Density Functional Theory"
    serial-number: 
      doi: 10.1007/3-540-12721-6 
```
