### ISSUE TITLE
Add YAML/JSON Schema

### ISSUE THREAD

**Issue by tsukinoko-kun** [typst/hayagriva#206]
Schema would be useful. It would be used like here for GitHub Actions:  
https://github.com/tsukinoko-kun/codehere/blob/main/.github/workflows/release.yml

```yaml
# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: goreleaser

on:
  create:
    tags:
      - "**"
```

This improves discoverability of features and reduces silly spelling issues.
