### ISSUE TITLE
APA: et al appears in reference list with same last name

### ISSUE THREAD

**Issue by yochem** [typst/hayagriva#209]
When the first authors of different reference list entries share a last name, the author section of the reference is `SharedLastName, A. et al`. This is  nowhere mentioned in the APA7 style guide. I'm unsure if this is a Hayagriva bug, or csl bug.

MWE:

<details><summary>refs.yml</summary>
<pre>
```yml
wangLightCSPNetLightweightNetwork2023:
  type: article
  title: '{LightCSPNet}: A lightweight network for image classification and objection detection'
  author:
  - Wang, Chuan
  - Liu, Qiang
  - Li, Yusheng
  - Gao, Mingwang
  date: 2023-03-31
  page-range: 46
  serial-number:
    #  doi: 10.1007/s44196-023-00226-5
    issn: 1875-6883
  parent:
    type: periodical
    title: International Journal of Computational Intelligence Systems
    issue: 1
    volume: 16
  url: https://doi.org/10.1007/s44196-023-00226-5
yolov10paper:
  type: Article
  title: '{YOLOv10}: Real-time end-to-end object detection'
  author:
  - Wang, Ao
  - Chen, Hui
  - Liu, Lihao
  - Chen, Kai
  - Lin, Zijia
  - Han, Jungong
  - Ding, Guiguang
  date: 2024-05-23
  publisher: ArXiv
  version: 1
  url: https://doi.org/10.48550/arXiv.2405.14458
kd-detr:
  type: article
  title: 'KD-DETR: Knowledge distillation for detection transformer with consistent distillation points sampling'
  author:
    - Wang, Yu
    - Li, Xin
    - Weng, Shengzhao
    - Zhang, Gang
    - Yue, Haixiao
    - Feng, Haocheng
    - Han, Junyu
    - Ding, Errui
  url: https://doi.org/10.48550/arXiv.2211.08071
  page-range: 16016-16025
  parent:
    type: proceedings
    title: Proceedings of the IEEE/CVF conference on computer vision and pattern recognition
    date: 2024-06-17
    publisher: IEEE
    location: Seattle, WA
yolov7:
  type: article
  title: 'YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors'
  author:
    - Wang, Chien-Yao
    - Bochkovskiy, Alexey
    - Liao, Hong-Yuan Mark
  url: https://doi.org/10.1109/CVPR52729.2023.00721
  page-range: 7464-7475
  parent:
    type: periodical
    date: 2023
    publisher: IEEE
    title: IEEE/CVF Conference on Computer Vision and Pattern Recognition
yolov9:
  type: article
  title: 'YOLOv9: Learning what you want to learn using programmable gradient information'
  author:
    - Wang, Chien-Yao
    - Yeh, I-Hau
    - Liao, Hong-Yuan Mark
  date: 2024
  publisher: ArXiv
  url: https://doi.org/10.48550/arXiv.2402.13616
</pre>
</details>

test.typ:
```typst
@yolov7
@yolov9
@yolov9
@wangLightCSPNetLightweightNetwork2023
@yolov10paper
@kd-detr

#bibliography("refs.yml", title: [References], style: "apa")
```

Produces:

![image](https://github.com/user-attachments/assets/8053b6f7-752c-4fa6-935d-bea1c36f221b)

Expected result is when we change the last names in something different, e.g. prepending a letter:

![image](https://github.com/user-attachments/assets/78ed5196-3abf-41b1-a230-7ed1ec38f782)

It also works fine when all author lists are changed to have only two authors (or 1).

Versions:
- typst 0.11.1
- LMK if other versions are of interest
