### ISSUE TITLE
Missing institution, report type, and report number

### ISSUE THREAD

**Issue by pohlm01** [typst/hayagriva#265]
When I cite an IETF RFC such as [RFC 6487](https://datatracker.ietf.org/doc/html/rfc6487), I expect the institution, report type, and report number to be included in the citation.
The below image shows the difference between the generated and expected results in a [minimal repoducable example](https://typst.app/project/rgdal114l7AZOP5nTmY5bt).
![image](https://github.com/user-attachments/assets/c9cae6bb-dccb-4c9f-8f2e-1a0f36035968)

First, I suspected the `ieee.csl` to miss this information, but to me, it looks like the CSL correctly includes them. Neither the `.bib` nor the hayagriva format seem to help.

**Comment by daeh** [comment]
Can confirm this affects `@report`, `@techreport`, `@thesis`, `@phdthesis`, and `@mastersthesis` entries across multiple styles (APA, Chicago, etc.).

As @zepinglee noted in [#112](https://github.com/typst/hayagriva/issues/112#issuecomment-1857693319):

> CSL use `publisher` field as report's institution or thesis's school and hayagriva doesn't map them correctly.

## Root Cause: CSL Field Mapping

The examples below use `@phdthesis` with CSL APA to illustrate the Hayagriva data mapping issue.

This is an example of a [published thesis rendered correctly per APA 7th edition](https://apastyle.apa.org/style-grammar-guidelines/references/examples/published-dissertation-references):

> Person, E. G. (2001). *A thesis title* [Doctoral dissertation, Some University]. SU Repository. <https://repo.some.edu/handle/10150/620615>

For Hayagriva to render this, the CSL data needs to be (per [CSL APA lines 810-820, 1677](https://github.com/citation-style-language/styles/blob/master/apa.csl)):
```csl
type: thesis
author: Person, Example G.
title: A thesis title
genre: Doctoral dissertation
publisher: Some University
archive: SU Repository
URL: https://repo.some.edu/handle/10150/620615
issued: 2001
```

Hayagriva's current mapping from YAML to CSL is (see [taxonomy.rs lines 259-268](https://github.com/typst/hayagriva/blob/main/src/csl/taxonomy.rs#L259)):

| Hayagriva | CSL |
|-----------|-----|
| `organization` | `authority` |
| `publisher` | `publisher` |
| `archive` | `archive` |

Thus, this Hayagriva YAML produces the correct APA 7th edition citation:
```yaml
eg-thesis:
  type: thesis
  author: Person, Example G.
  title: A thesis title
  genre: Doctoral dissertation
  publisher: Some University
  archive: SU Repository
  url: https://repo.some.edu/handle/10150/620615
  date: 2001
```

However, Hayagriva maps BibLaTeX fields differently (see [interop.rs line 521](https://github.com/typst/hayagriva/blob/main/src/interop.rs#L521)):

| BibLaTeX | Hayagriva | CSL |
|----------|-----------|-----|
| `institution` | `organization` | `authority` |
| `publisher` | `publisher` | `publisher` |
| (none) | `archive` | `archive` |

Thus, the BibLaTeX that renders correctly in LaTeX:
```bibtex
@phdthesis{eg-thesis,
  author      = {Person, Example G.},
  title       = {A thesis title},
  institution = {Some University},
  publisher   = {{SU Repository}},
  url         = {https://repo.some.edu/handle/10150/620615},
  date        = {2001}
}
```
produces a malformed citation in Typst:
> Person, E. G. (2001). *A thesis title* [Doctoral dissertation, SU Repository]. <https://repo.some.edu/handle/10150/620615>

**The problem with BibLaTeX data in Hayagriva:**
- `institution` ends up in CSL `authority`, which most CSL styles (including APA) ignore for thesis/report entries
- `publisher` ends up in CSL `publisher`, which CSL styles typically use for institution
- No BibLaTeX field maps to CSL `archive`, so database/repository information cannot be rendered

**BibLaTeX has no workaround**: the field mapping in `interop.rs` needs to be fixed for thesis/report types.

**Summary:**

The core issue is that BibLaTeX `institution` → Hayagriva `organization` → CSL `authority`, but CSL styles expect institution data in `publisher` for thesis and report entries. This affects multiple entry types (`@thesis`, `@phdthesis`, `@mastersthesis`, `@report`, `@techreport`) and multiple CSL styles (APA, IEEE, Chicago, etc.).

**Potential fix:**

For thesis and report entry types:
- Map BibLaTeX `institution` → Hayagriva `publisher` → CSL `publisher`
- Map BibLaTeX `publisher` → Hayagriva `archive` → CSL `archive`

<details>
<summary><strong>BibLaTeX examples</strong></summary>

One workaround that has been suggested (e.g., #112) is to use `publisher` instead of `institution`. However, this raises several issues:

1. **`publisher` is incorrectly used as institution**. The `publisher` value appears where the institution should be. At a minimum, this creates an interoperability issue with BibLaTeX.
2. **It's often not possible to render the `publisher` correctly.** Since `publisher` is treated as the `institution`, actual publisher data does not have a route into CSL.
   - **`institution` and `publisher` cannot be jointly rendered** in BibLaTeX. It does not currently seem possible to comply with styles where both are required.

### Example 1: `@phdthesis` with `institution` and `publisher`

```bibtex
@phdthesis{eg-thesis,
  author      = {Person, Example G.},
  title       = {A thesis title},
  institution = {Some University},
  publisher   = {{SU Repository}},
  url         = {https://repo.some.edu/handle/10150/620615},
  date        = {2001}
}
```

**LaTeX output (correct):**
```
Person, E. G. (2001). A thesis title [Doctoral dissertation, Some University]. SU Repository. https://repo.some.edu/handle/10150/620615
```

**Typst output**:
```
Person, E. G. (2001). A thesis title [Doctoral dissertation, SU Repository]. https://repo.some.edu/handle/10150/620615
```

The `institution` ("Some University") is dropped, and `publisher` ("SU Repository") incorrectly appears inside the brackets where the institution should be.

### Example 2: `@phdthesis` with `publisher` only (with URL)

```bibtex
@phdthesis{eg-thesis,
  author      = {Person, Example G.},
  title       = {A thesis title},
  publisher   = {Some University},
  url         = {https://repo.some.edu/handle/10150/620615},
  date        = {2001}
}
```

**Typst output**:
```
Person, E. G. (2001). A thesis title [Doctoral dissertation, Some University]. https://repo.some.edu/handle/10150/620615
```

This works when using `publisher` for the institution, but you cannot then specify a database/repository.

### Example 3: `@phdthesis` with `publisher` only (no URL)

```bibtex
@phdthesis{eg-thesis,
  author      = {Person, Example G.},
  title       = {A thesis title},
  publisher   = {Some University},
  date        = {2001}
}
```

**Typst output**:
```
Person, E. G. (2001). A thesis title [Doctoral dissertation]. Some University.
```

Without a URL/DOI, Hayagriva-CSL treats this as an [unpublished dissertation](https://apastyle.apa.org/style-grammar-guidelines/references/examples/unpublished-dissertation-references), placing the institution outside the brackets. This differs from BibLaTeX which still places institution inside brackets (`Person, E. G. (2001). A thesis title [Doctoral dissertation, Some University].`).

</details>

<details>
<summary><strong>Hayagriva YAML examples</strong></summary>

### Example 1: Using `archive` field (correct)

```yaml
eg-thesis:
  type: thesis
  author: Person, Example G.
  title: A thesis title
  genre: Doctoral dissertation
  publisher: Some University
  archive: SU Repository
  url: https://repo.some.edu/handle/10150/620615
  date: 2001
```

**Output** (correct):
```
Person, E. G. (2001). A thesis title [Doctoral dissertation, Some University]. SU Repository. https://repo.some.edu/handle/10150/620615
```

Using `publisher` for institution and `archive` for database produces the correct output per APA 7th edition.

### Example 2: Organization field (fails)

```yaml
eg-thesis:
  type: thesis
  author: Person, Example G.
  title: A thesis title
  genre: Doctoral dissertation
  organization: Some University
  publisher: SU Repository
  url: https://repo.some.edu/handle/10150/620615
  date: 2001
```

**Output**:
```
Person, E. G. (2001). A thesis title [Doctoral dissertation, SU Repository]. https://repo.some.edu/handle/10150/620615
```

The `organization` field is ignored. Same problem as BibLaTeX `institution`.

### Example 3: Nested publisher (doesn't help)

[#214](https://github.com/typst/hayagriva/pull/214) added support for nested `publisher` fields with `name` and `location` subfields (see issue #86). The `location` field is for publisher city (e.g., "Cambridge, MA"), not for database names.

```yaml
eg-thesis:
  type: thesis
  author: Person, Example G.
  title: A thesis title
  genre: Doctoral dissertation
  publisher:
    name: Some University
    location: Cambridge, MA
  url: https://repo.some.edu/handle/10150/620615
  date: 2001
```

**Output**:
```
Person, E. G. (2001). A thesis title [Doctoral dissertation, Some University]. https://repo.some.edu/handle/10150/620615
```

The `location` field is not rendered because CSL APA does not include publisher city for theses. (CSL IEEE does render it: "Some University, Cambridge, MA".) This feature does not help with the institution/database problem.

### Example 4: Genre hack (incorrect output)

```yaml
eg-thesis:
  type: thesis
  author: Person, Example G.
  title: A thesis title
  genre: Doctoral dissertation, Some University
  publisher: SU Repository
  url: https://repo.some.edu/handle/10150/620615
  date: 2001
```

**Output**:
```
Person, E. G. (2001). A thesis title [Doctoral dissertation, Some University, SU Repository]. https://repo.some.edu/handle/10150/620615
```

This shows both institution and publisher, but incorrectly places both inside the brackets. The correct APA 7th edition format should have the database *after* the brackets.

</details>

---

Environment: Typst 0.14.2, Hayagriva 0.9.1
