### ISSUE TITLE
Support BibTex `shortauthor` and an equivalent for yaml

### ISSUE THREAD

**Issue by John-Toohey** [typst/hayagriva#278]
When citing organizations it is not uncommon to want to abbreviate their name (e.g. "BBC" for "British Broadcasting Corporation"). In BibTex this is implemented through the `shortauthor` field. To my knowledge, There is no recognition of this field in Hayagriva and no equivalent in the YAML representation.

As for the YAML representation, a possible solution could be to change the type of a `person` to allow input something akin to:

```yaml
# ...
  author:
    name: British Broadcasting Corporation
    shortname: BBC
# ...
```

Or, equivalently for an array of authors:

```yaml
# ...
  author:
    - name: British Broadcasting Corporation
      shortname: BBC
    - Doe, John
# ...
```

If this feature is already implemented and I am just being inept I apologize.

Nevertheless, thank you overall for this piece of software. Should my proposal be desirable I can try my hand at implementing it.
