### ISSUE TITLE
Weired justifying in bibliography

### ISSUE THREAD

**Issue by JL710** [typst/hayagriva#283]
this is what my yaml looks like:
```
un-sicherheitsrat-bpb:
  type: web
  url:
    value: https://www.bpb.de/themen/internationale-organisationen/vereinte-nationen/48583/sicherheitsrat-der-vereinten-nationen/
    date: 2025-03-01
```
This is how it renders justified in typst:
![Image](https://github.com/user-attachments/assets/df9cd559-9fb2-41cd-ad95-244734e20df6)

I opened a post on discord and a team member told me it is a hayagriva issue.
They mentioned that it could be that the `[7]` is considered in the justify.
