### ISSUE TITLE
Hayagriva doesn't support APA's Director, Writer, nor Producer fields for TV broadcasts

### ISSUE THREAD

**Issue by ironupiwada** [typst/hayagriva#300]
### Description

There has been a bug found by the user frrn on [Discord](https://discordapp.com/channels/1054443721975922748/1357811113667854486/1357811113667854486), and I confirm it by myself.

An example:

```
barille_nace_1979:
  type: scene
  title: "I la Terrra va ser"
  author: "Barillé, Albert"
  affiliated:  
    - role: writer
      names: ["Barillé, Albert"]
    - role: director
      names: ["Barillé, Albert"]
    - role: producer
      names: ["Barillé, Albert"]
  date: 1979
  language: "fr"
  url: "https://www.imdb.com/title/tt0758231/"
  parent:
    type: video
    title: "Una vegada hi havia... l'home"
    issue: 1
    publisher:
      name: "Procidis"
      location: "França"
    date: 1978
```
Coupled with the APA 7 official style, it results in such an output:

![Image](https://github.com/user-attachments/assets/264f07ca-dee0-47d0-9acf-d2493b44d76c)

Aside from the usual Author field, neither Writer (CSL's script-writer), nor Producer and Director role fields are supported by Hayagriva. Look at this source code: https://github.com/citation-style-language/styles/blob/master/apa.csl. In relation to broadcasts (both radio and TV ones), at least the Director or Writer fields should be applied (strangely they aren't, though Hayagriva claims itself to distinguish the scene/video combination).

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst
