### ISSUE TITLE
`demote-non-dropping-particle` has no effect on the sort order

### ISSUE THREAD

**Issue by fungai2000** [typst/hayagriva#311]
Hello. Over on the [Typst Forum](https://forum.typst.app/t/how-to-ignore-strings-in-bibliography-sorting/3846/15), I raised the question of how to ignore certain strings or particles in the sort order of the bibliography. After some testing, it appears that whatever value one places after `demote-non-dropping-particle` (“never”, “sort-only”, "display-and-sort") has no effect when the surname begins with a particle with a hyphen (`al-`).

What drove me to this was a desire to ignore the Arabic particle `al-` used in surnames, when sorting the bibliography (similar to how “von” in “Alexander von Hunstyles.org/en/stable/specification.html#name-particles), `al-` in a name such as "al-Hakim" should be ignored and should be filed under `H` rather than `A` in the bibliography.

We tested this with a number of Chicago CSL styles (chicago-library-list-mod.csl, chicago-library-list.csl, etc.) all to no avail. I also tested it with both a Hayagriva.yml file and BibTeX file. Our only conclusion was that the Bibliography parser was not accounting for the `demote-non-dropping-particle` instruction.

Take for example the following short list :

```
al-tahanawi1996:
  type: Book
  title: "Kashshāf iṣṭilāḥāt al-funūn wa-l-ʿulūm"
  author: al-Tahānawī, Muḥammad ʿAlī
  publisher:
    name: Maktabat Lubnān Nāshirūn
    location: Beirut
  date: 1996

haydar1991:
  type: Book
  title: "Durar al-ḥukkām fī sharḥ Majallat al-aḥkām"
  author: Haydar, ʿAlī
  publisher:
    name: Dār al-Jīl
    location: Beirut
  date: 1991

al-hakim1938
  type: Book
  title: A sparrow from the east
  author: al-Hakim, Tawfik
  publisher:
    name: Dār al-Sharq
    location: Cairo
  date: 1938
```

If the particle were to be correctly ignored, the order upon processing the document should be:
1. al-Hakim
2. Haydar
3. al-Tahanawi
