### ISSUE TITLE
prose citations do not collapse

### ISSUE THREAD

**Issue by retroflexivity** [typst/hayagriva#322]
With an author-date style that has collapsing enabled, normal citations collapse properly, omitting the repeating author, but prose citations do not.

```typ
@jones1 @jones2

#cite(<jones1>, form: "prose") #cite(<jones2>, form: "prose")

#bibliography("ref.yml", style: "chicago-author-date")
```
gives this:

![Image](https://github.com/user-attachments/assets/68fcfe1a-68d4-4d77-b1ac-db64c40a88e8)

What I would expect is this, with the author appearing only once and years collapsed into the same parenthesis (at least this is what biblatex does):

![Image](https://github.com/user-attachments/assets/dd830b83-4831-4ba9-bcae-05c6a19f2d2b)

(here's the yml)
```yml
jones1:
  type: Manuscript
  title: Foo
  author: Jones, John
  date: 2000
jones2:
  type: Manuscript
  title: Bar
  author: Jones, John
  date: 2005
```
