### ISSUE TITLE
JSONschema for hayagriva file

### ISSUE THREAD

**Issue by clbarnes** [typst/hayagriva#33]
Somewhat related to #32; it would be much easier to interact with the YAML file from other languages if there was a programmatic schema for it.

**Comment by nichtich** [comment]
A JSON Schema would also help to formalize the partly vague File Format specification. By now some parts are not strictly defined but only shown as examples. This is not related to #32 - JSON Schema just happens to be common with implementations in several programming language to validate both JSON and YAML files.

**Comment by bdarcus** [comment]
And you can write and maintain the schema in YAML, which is much nicer, give it's support for comments and such, and just run a CI process to create a JSON version.

```yaml
        institution:
          title: Literal name text; should not be parsed
          # comment
          description: Use for institutional creator names; e.g. 'National Institutes of Health'
          type: string
```

BTW, presumably this means you don't really support corporate names in these author lists?

```yaml
    author:  ["Doe, Jane", "Some org, Some subunit"]
```
