### ISSUE TITLE
Negative dates incorrectly get A.D. suffix

### ISSUE THREAD

**Issue by fedelebron** [typst/hayagriva#333]
Test case:

```
elements:
  type: Book
  author: "Euclid"
  title: "Elements"
  date: -300
```

This is rendered as `Euclid, Elements, 301AD`. But this was not anno-domini ("year of our lord") 301, but rather 300 years before christ, so the right suffix is "B.C."
