### ISSUE TITLE
one-off error in citing web url in bibliography apa format

### ISSUE THREAD

**Issue by Sycration** [typst/hayagriva#51]
In main.typ:
```
#cite("huh")
#bibliography("huh.yml", style: "apa")
```

In huh.yml
```yml
huh:
  type: Web
  title: Webpage
  date: 2023-01-01
  url: 
    value: https://example.com
    date: 2023-01-01
```

What renders:
![image](https://github.com/typst/typst/assets/48634717/3a55734b-cec2-4723-9ebb-6bd93e9ea149)
