### ISSUE TITLE
verbatim: true not working (or misunderstood?)

### ISSUE THREAD

**Issue by jeanas** [typst/hayagriva#56]
Consider this file `tmp.yml`:

```
foo-article:
  type: Article
  author: Foo Bar
  date: 2023
  title:
    value: SCCs are great
    verbatim: true
```

Running

```
$ hayagriva tmp.yml  reference
```

outputs

```
Foo Bar. 2023. Sccs Are Great.
```

It changed "SCCs" to "Sccs" in spite of `verbatim: true`. What am I missing?
