### ISSUE TITLE
Unclosed italic delimiter in terminal output

### ISSUE THREAD

**Issue by jeanas** [typst/hayagriva#57]
`tmp.yml`:

```
schewe-original:
  type: Article
  author: Sven Schewe
  title: Beyond Hyper-Minimisation — Minimising DBAs and DPAs is NP-Complete
  doi: "10.4230/LIPIcs.FSTTCS.2010.400"
  date: 2010
  parent:
    type: Periodical
```

![image](https://github.com/typst/hayagriva/assets/37271310/0b68e0ad-b4b1-4551-8cdd-6a17232d81b1)

Note how the terminal prompt appears in italics after the `hayagriva` invocation, which means there are unclosed escape sequences in the Hayagriva output.
