### ISSUE TITLE
non-integer chapter serial numbers are not rendered

### ISSUE THREAD

**Issue by classabbyamp** [typst/hayagriva#60]
example:

```
bovik2005handbook:
  type: chapter
  title: Image Noise Models
  serial-number: 4.5
  author: Boncelet, Charles
  date: 2005
  edition: 2
  page-range: 397-405
  parent:
    title: Handbook of image and video processing
    editor: Bovik, Alan C.
    publisher: Elsevier Academic Press
    isbn: 978-0-12119792-6
```

rendered in typst using `ieee.typ`:
![image](https://github.com/typst/hayagriva/assets/5366828/4d0066fc-0858-4518-86f2-c05affb837e2)

expected: `... Press, ch. 4.5, pp. 397-405.`

**Comment by aaron-jack-manning** [comment]
This is nothing to do with the fact that the chapter is not an integer. Changing the serial number to `4` does not resolve the problem. The `ieee.csl` file does not render this data at all, but it is passed to the CSL file as the `number` variable. This can be seen by trying `apa` style instead, where the data is rendered (see line `1280` of [the CSL file](https://raw.githubusercontent.com/citation-style-language/styles/26eccff9e537f71494a4da7b91afac1adf571dc9/apa.csl)).

I think the actual bug here is that the value is passed from Hayagriva as `number` and not `chapter-number`, which seems to be what the CSL file is actually looking for (at least that is what IEEE is using).

**Comment by Braintelligence** [comment]
The title says "non-integer", but an integer value fails the same way.

`ch.yaml`

```yaml
int:
  type: chapter
  title: Integer serial number
  author: Ann Author
  serial-number: 5
  page-range: 397-405
  parent:
    type: book
    title: A book
    publisher: Press
    date: 2020

frac:
  type: chapter
  title: Non-integer serial number
  author: Ben Bookman
  serial-number: 4.5
  page-range: 397-405
  parent:
    type: book
    title: A book
    publisher: Press
    date: 2020

quoted:
  type: chapter
  title: Quoted serial number
  author: Cora Curator
  serial-number: "4.5"
  page-range: 397-405
  parent:
    type: book
    title: A book
    publisher: Press
    date: 2020
```

`ch.typ`

```typst
#bibliography("ch.yaml", style: "ieee", full: true)
```

Output:

```
[1] Ann Author, "Integer serial number," in A book, Press, 2020, pp. 397-405.
[2] Ben Bookman, "Non-integer serial number," in A book, Press, 2020, pp. 397-405.
[3] Cora Curator, "Quoted serial number," in A book, Press, 2020, pp. 397-405.
```

<img width="1339" height="178" alt="Image" src="https://github.com/user-attachments/assets/9e7b6027-3fc0-4758-ae66-12f0348a0a5a" />

None of the three shows a chapter number, so the value format is not what decides it.

`ieee.csl` renders the chapter number from the CSL variable `chapter-number`, not `number`:

```xml
<group delimiter=" ">
  <label variable="chapter-number" form="short"/>
  <text variable="chapter-number"/>
</group>
```

That points at a missing mapping from a chapter's `serial-number` to `chapter-number` rather than at number parsing, in the same class as #403 ("When type is `entry`, it seems its `parent`'s title doesn't get translated to CSL `container-title`").

hayagriva 0.10.1 (Typst 0.15.1)
