### ISSUE TITLE
Unicode characters are messed up when doing bib -> yml conversion

### ISSUE THREAD

**Issue by Enivex** [typst/hayagriva#67]
Running `hayagriva .\references.bib > converted.yml` on the following file

```
@Article{Euler1757,
  author  = {Euler, Leonhard},
  journal = {Mémoires de l'académie des sciences de Berlin},
  title   = {Principes généraux du mouvement des fluides},
  year    = {1757},
  pages   = {274--315},
}

@Comment{jabref-meta: databaseType:bibtex;}
```
results in
```
---
Euler1757:
  type: article
  parent:
    - type: periodical
      title:
        value: "M├⌐moires de l'acad├⌐mie des sciences de Berlin"
        sentence-case: "M├⌐moires de l'acad├⌐mie des sciences de berlin"
  date: 1757
  page-range: 274-315
  author: "Euler, Leonhard"
  title: Principes g├⌐n├⌐raux du mouvement des fluides
```

If I simply do print to the terminal with `hayagriva .\references.bib` it's displayed correctly

![image](https://github.com/typst/hayagriva/assets/2191754/1714f6f3-119c-4fb7-ba2e-1860d587a622)

so it seems like the issue is in writing the actual file
