### ISSUE TITLE
Series of Books

### ISSUE THREAD

**Issue by DerDrodt** [typst/hayagriva#71]
Assume a BibLaTeX entry like:
```bib
@book{DBLP:series-lncs-10001,
  editor       = {Wolfgang Ahrendt and Bernhard Beckert and Richard Bubel and Reiner H{\"{a}}hnle and Peter H. Schmitt and Mattias Ulbrich},
  title        = {Deductive Software Verification -- The {KeY} Book},
  subtitle     = {From Theory to Practice},
  series       = {Lecture Notes in Computer Science},
  volume       = {10001},
  publisher    = {Springer},
  year         = {2016},
  url          = {https://doi.org/10.1007/978-3-319-49812-6},
  doi          = {10.1007/978-3-319-49812-6},
  isbn         = {978-3-319-49811-9},
  timestamp    = {Tue, 14 May 2019 10:00:55 +0200},
  biburl       = {https://dblp.org/rec/series/lncs/10001.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}
```

How would I encode the series of the book in Hayagriva? There is no field for this nor is there a fitting entry type that could be a parent.

**Comment by DerDrodt** [comment]
But then I am not sure that the translation works properly.

Using the CLI, I am given:
```yml
DBLP:series-lncs-10001:
  type: book
  title: Deductive Software Verification -- The {KeY} Book
  date: 2016
  editor:
  - Ahrendt, Wolfgang
  - Beckert, Bernhard
  - Bubel, Richard
  - Hähnle, Reiner
  - Schmitt, Peter H.
  - Ulbrich, Mattias
  publisher: Springer
  volume: 10001
  url: https://doi.org/10.1007/978-3-319-49812-6
  serial-number:
    doi: 10.1007/978-3-319-49812-6
    isbn: 978-3-319-49811-9
  parent:
    type: book
    title: Lecture Notes in Computer Science
```

Typst then writes the volume after the book title _and_ the series title. It seems there is some confusion what to do with the volume when it comes to a series of books.
