### ISSUE TITLE
`editor` and `affiliated` doesn't render well with APA.

### ISSUE THREAD

**Issue by JuanM04** [typst/hayagriva#73]
In my Typst document, using `#bibliography("bibliography.yml", style: "apa")` and `#set text(lang: "es")`, and having this `bibliography.yml`:

```yml
stallings:
  type: Book
  title: Sistemas operativos
  author: Stallings, William
  editor: Martín-Romo, Miguel
  affiliated:
    - role: translator
      names:
        - Peña Sánchez, José María
        - Pérez Costoya, Fernando
        - de los Santos Pérez Hernández, María
        - Robles Forcada, Víctor
        - Rosales García, Francisco Javier
  publisher: Pearson Educación
  edition: 5
  date: 2005
  serial-number:
    isbn: 84-205-4462-0
  language: es
  page-total: 872
```

The reference renders like this:

![image](https://github.com/typst/hayagriva/assets/16712703/9e632dc2-cd64-42a5-9416-a14ddf1eedff)

Notice the double `;` and the missing `;` between the editor and the translators.
