### ISSUE TITLE
Date ranges

### ISSUE THREAD

**Issue by genericusername3** [typst/hayagriva#75]
Many conferences (and thus, conference proceedings) have date ranges instead of dates, and I'd like to specify the start and end date of a conference. One option would be to follow the ISO 8601 standard (or at least [what Wikipedia claims it is](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)), and use `<start-date>/<end-date>`, like so:

```yaml
[...]
  parent:
    type: proceedings
    publisher: IEEE
    date: '2022-05-16/2022-05-19'
    title:
      value: 2022 22nd IEEE International Symposium on Cluster, Cloud and Internet
        Computing (CCGrid)
      short: 2022 22nd IEEE Int. Symp. Cluster, Cloud and Internet Comput. (CCGrid)
    location: Taormina, Italy
```

Could there be an option for this?

**Comment by yochem** [comment]
Or subfields?

So normally:
```yml
date: 2022-05-16
```

Range:
```yml
date:
  start: 2022-05-16
  end: 2022-05-19
```

Or since `page-range` exists, it could also be called `date-range`. But that's probably more confusing.
