### ISSUE TITLE
Article number

### ISSUE THREAD

**Issue by yochem** [typst/hayagriva#84]
An article can also use an article number instead of a page range: https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references#2269009005. Is this currently supported? I couldn't find the key for it.

**Comment by zepinglee** [comment]
Biblatex has an `eid` field for that but hayagriva doesn't recognize it at the moment. I've found one working method: adding 
the article number with key `serial` in the `serial-number` field. The following is a full example.

```yaml
10.1:6:
  type: article
  title: Body Ownership Increases the Interference Between Observed and Executed Movements
  author:
  - Burin, D.
  - Kilteni, K.
  - Rabuffetti, M.
  - Slater, M.
  - Pia, L.
  date: 2019
  serial-number:
    doi: 10.1371/journal.pone.0209899
    serial: e0209899
  parent:
    type: periodical
    title: 'PLOS ONE'
    issue: 1
    volume: 14
```

> Burin, D., Kilteni, K., Rabuffetti, M., Slater, M., & Pia, L. (2019). Body Ownership Increases the Interference Between Observed and Executed Movements. PLOS ONE, 14(1), Article e209899. https://doi.org/10.1371/journal.pone.0209899


This is deduce the from the code below but not found in the documentation.

https://github.com/typst/hayagriva/blob/b5a3d1a6cd7793de100eef2cb641efcc7cb8acb2/src/csl/taxonomy.rs#L147-L153
