### ISSUE TITLE
punctuation-in-quote seemingly not considered

### ISSUE THREAD

**Issue by DerDrodt** [typst/hayagriva#85]
I have a hayagriva entry like
```yml
JMLRefMan:
  type: report
  title: Java Modeling Language (JML) Reference Manual
  author:
    - Cok, David R.
    - Leavens, Gary T.
    - Ulbrich, Mattias
  date: 2022-07-01
  edition: 2
  url:
    value: https://www.openjml.org/documentation/JML_Reference_Manual.pdf
    date: 2023-11-23
```

And I use a CSL style with:
```xml
<locale xml:lang="en">
    <style-options punctuation-in-quote="true" />
    <!-- ... -->
  </locale>
```

Hayagriva gives me the ouput: 
```
[1] D.  R.  Cok,  G.  T.  Leavens,  and  M.  Ulbrich,  “Java  Modeling  Language  (JML)  Reference  Man-
ual”, 2nd ed., Jul. 2022. Accessed: Nov. 23, 2023. [Online]. Available: https://www.openjml.org/
documentation/JML_Reference_Manual.pdf
```

As can be seen, the punctuation is not moved into the title's quotation marks. Zotero handles this correctly, so the CSL seems to be correct.

I was also unable to find a test case for `punctuation-in-quote`.
