### ISSUE TITLE
Conference proceedings published as a book chapter

### ISSUE THREAD

**Issue by yochem** [typst/hayagriva#94]
I'm wondering how to cite a conference proceedings published as book chapter in APA:

Bedenel, A.-L., Jourdan, L., & Biernacki, C. (2019). Probability estimation by an adapted genetic algorithm in web insurance. In R. Battiti, M. Brunato, I. Kotsireas, & P. Pardalos (Eds.), Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization (pp. 225–240). Springer. https://doi.org/10.1007/978-3-030-05348-2_21

I tried:
```yml
test:
  type: chapter
  author:
    - Bedenel, A. L.
    - Jourdan, L.
    - Biernacki, C.
  date: 2019
  title: Probability estimation by an adapted genetic algorithm in web insurance
  page-range: 225–240
  serial-number:
    doi: 10.1007/978-3-030-05348-2_21
  parent:
    type: book
    editor:
      - Battiti, R.
      - Brunato, M.
      - Kotsireas, I.
      - Pardalos, P.
    title: 'Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization'
    publisher: Springer
```

Result:
Bedenel, A. L., Jourdan, L., & Biernacki, C. (2019). Probability estimation by an adapted genetic algorithm in web insurance. In Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization (pp. 225–240). Springer. https://doi.org/10.1007/978-3-030-05348-2_21

When changing `editor` to `author`, we almost get the desired result, but missing the (Eds.) part of course:

Bedenel, A. L., Jourdan, L., & Biernacki, C. (2019). Probability estimation by an adapted genetic algorithm in web insurance. In R. Battiti, M. Brunato, I. Kotsireas, & P. Pardalos, Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization (pp. 225–240). Springer. https://doi.org/10.1007/978-3-030-05348-2_21

It thus seems that `parent.editor` is skipped on book chapters, but `parent.author` is not.

As a side question: how to get the "Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization" part right? I would expect to create a parent of the book with title "Learning and intelligent optimization" and volume 11353. That parent would be series/periodical with title "Lecture notes in computer science".

**Comment by yochem** [comment]
found it: editor should not be in the parent, but in the main part. I would still argue this is unexpected, since they are the editors of the whole book, not the chapter.

**Comment by zepinglee** [comment]
I try to fix this issue in #96 and it work the previous bib data.

> Bedenel, A. L., Jourdan, L., & Biernacki, C. (2019). Probability estimation by an adapted genetic algorithm in web insurance. In R. Battiti, M. Brunato, I. Kotsireas, & P. Pardalos (Eds.), Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization (pp. 225–240). Springer. https://doi.org/10.1007/978-3-030-05348-2_21

BTW, does hayagriva have the `volume-title` field? In that way the title `'Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization'` can be split into three fields: `title`, `volume`, and `volume-title`.

**Comment by yochem** [comment]
> BTW, does hayagriva have the volume-title field? In that way the title 'Lecture notes in computer science: Vol. 11353. Learning and intelligent optimization' can be split into three fields: title, volume, and volume-title.

I was really hoping that hayagriva supported this. IMO, it would make more sense to add the series as a parent of the parent:

```yml
test:
  type: chapter
  author:
    - Bedenel, A. L.
    - Jourdan, L.
    - Biernacki, C.
  date: 2019
  title: Probability estimation by an adapted genetic algorithm in web insurance
  page-range: 225–240
  serial-number:
    doi: 10.1007/978-3-030-05348-2_21
  parent:
    type: book
    volume: 11353
    editor:
      - Battiti, R.
      - Brunato, M.
      - Kotsireas, I.
      - Pardalos, P.
    title: 'Learning and intelligent optimization'
    publisher: Springer
    parent:
      title: Lecture notes in computer science
      type: periodical/book
```
